# Generated by Django 5.2.6 on 2026-08-07 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='мэргэжил')),
                ('years_of_service', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ажилласан жил')),
                ('education', models.TextField(blank=True, verbose_name='боловсрол')),
                ('bio', models.TextField(blank=True, verbose_name='өөрийн тухай')),
                ('is_employed', models.BooleanField(default=True, verbose_name='ажиллаж байгаа')),
            ],
            options={
                'verbose_name': 'багшийн профайл',
                'verbose_name_plural': 'багшийн профайлууд',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='хэрэглэгчийн нэр')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='и-мэйл')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='утас')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='овог')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='нэр')),
                ('is_active', models.BooleanField(default=True, verbose_name='идэвхтэй')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Django admin хандах')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'хэрэглэгч',
                'verbose_name_plural': 'хэрэглэгчид',
            },
        ),
        migrations.CreateModel(
            name='GuardianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note', models.TextField(blank=True, verbose_name='тэмдэглэл')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'эцэг эхийн профайл',
                'verbose_name_plural': 'эцэг эхийн профайлууд',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('superadmin', 'Системийн администратор'), ('admin', 'Цэцэрлэгийн администратор'), ('teacher', 'Багш'), ('guardian', 'Эцэг эх, асран хамгаалагч')], max_length=20, verbose_name='эрх')),
                ('is_active', models.BooleanField(default=True, verbose_name='идэвхтэй')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='эхэлсэн огноо')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'гишүүнчлэл',
                'verbose_name_plural': 'гишүүнчлэлүүд',
            },
        ),
    ]
