# Generated by Django 5.2.6 on 2026-08-08 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginattempt_passwordresettoken'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('delivery', models.CharField(choices=[('email', 'И-мэйл'), ('paper', 'Цаасан код'), ('both', 'И-мэйл ба цаасан код')], default='both', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='tenants.kindergarten')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'урилга',
                'verbose_name_plural': 'урилгууд',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'used_at'], name='accounts_in_user_id_2a34c8_idx')],
            },
        ),
    ]
