# Generated by Django 5.2.6 on 2026-08-17 10:53
"""Catches up the `verbose_name` on `Membership.kindergarten`.

`sqlmigrate` prints `(no-op)`: a label is Django-side state only and touches
no column. It is recorded anyway because the model and the migration graph
had drifted, so `makemigrations --check` failed on a clean tree — which is
the check a deploy relies on to prove no *real* schema change is pending.
The label reaches the admin (CLAUDE.md §5, RFP §611).
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_invitation'),
        ('tenants', '0002_group_age_band'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='kindergarten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.kindergarten', verbose_name='цэцэрлэг'),
        ),
    ]
