# Generated by Django 5.2.6 on 2026-08-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_membership_kindergarten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Системийн администратор'), ('admin', 'Цэцэрлэгийн администратор'), ('teacher', 'Багш'), ('guardian', 'Эцэг эх, асран хамгаалагч'), ('accountant', 'Нягтлан')], max_length=20, verbose_name='эрх'),
        ),
    ]
