# Generated by Django 5.2.6 on 2026-08-09 07:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0002_remove_enrollment_uniq_enrollment_per_year_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='нэр')),
                ('is_default', models.BooleanField(default=False, help_text='Шинэ үнэлгээнд сонгогдох шат', verbose_name='үндсэн шат')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(blank=True, help_text='Хоосон бол системийн үндсэн шат', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten', verbose_name='цэцэрлэг')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'үнэлгээний шат',
                'verbose_name_plural': 'үнэлгээний шатууд',
                'ordering': ['kindergarten__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='утга')),
                ('label', models.CharField(max_length=100, verbose_name='нэр')),
                ('color', models.CharField(default='#94a3b8', max_length=7, verbose_name='өнгө')),
                ('description', models.TextField(blank=True, verbose_name='тайлбар')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='assessment.assessmentscale')),
            ],
            options={
                'verbose_name': 'үнэлгээний түвшин',
                'verbose_name_plural': 'үнэлгээний түвшнүүд',
                'ordering': ['scale', 'value'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='нэр')),
                ('code', models.SlugField(help_text='Системийн доторх тогтмол нэр. Тайланд харагдахгүй.', verbose_name='код')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='эрэмбэ')),
                ('is_active', models.BooleanField(default=True, verbose_name='идэвхтэй')),
                ('color', models.CharField(default='#6366f1', help_text='Графикт хэрэглэх өнгө, ж: #6366f1', max_length=7, verbose_name='өнгө')),
                ('description', models.TextField(blank=True, verbose_name='тайлбар')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(blank=True, help_text='Хоосон бол системийн үндсэн жагсаалт — бүх цэцэрлэгт нийтлэг', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten', verbose_name='цэцэрлэг')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'хөгжлийн чиглэл',
                'verbose_name_plural': 'хөгжлийн чиглэлүүд',
                'ordering': ['order', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevelopmentIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='нэр')),
                ('age_from', models.PositiveSmallIntegerField(default=2, verbose_name='хамрах нас (эхлэх)')),
                ('age_to', models.PositiveSmallIntegerField(default=5, verbose_name='хамрах нас (дуусах)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='эрэмбэ')),
                ('is_active', models.BooleanField(default=True, verbose_name='идэвхтэй')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='assessment.developmentdomain')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'хөгжлийн шалгуур',
                'verbose_name_plural': 'хөгжлийн шалгуурууд',
                'ordering': ['domain', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='улирал')),
                ('name', models.CharField(max_length=50, verbose_name='нэр')),
                ('starts_on', models.DateField(verbose_name='эхлэх огноо')),
                ('ends_on', models.DateField(verbose_name='дуусах огноо')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='tenants.schoolyear')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'улирал',
                'verbose_name_plural': 'улирлууд',
                'ordering': ['school_year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('comment', models.TextField(blank=True, verbose_name='тайлбар')),
                ('visible_to_parents', models.BooleanField(default=False, verbose_name='эцэг эхэд харагдах')),
                ('assessed_at', models.DateTimeField(auto_now=True, verbose_name='үнэлсэн огноо')),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='children.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='children.enrollment')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assessment.assessmentlevel', verbose_name='үнэлгээ')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessment.developmentdomain', verbose_name='хөгжлийн чиглэл')),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assessment.developmentindicator')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessment.term', verbose_name='улирал')),
            ],
            options={
                'verbose_name': 'хөгжлийн үнэлгээ',
                'verbose_name_plural': 'хөгжлийн үнэлгээ',
                'ordering': ['-term__number', 'domain__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentlevel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('scale', 'value'), name='uniq_level_value_per_scale'),
        ),
        migrations.AddConstraint(
            model_name='developmentdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('kindergarten__isnull', True)), fields=('code',), name='uniq_domain_system_code'),
        ),
        migrations.AddConstraint(
            model_name='developmentdomain',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('kindergarten__isnull', False)), fields=('kindergarten', 'code'), name='uniq_domain_kindergarten_code'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['school_year', 'starts_on', 'ends_on'], name='assessment__school__47bc58_idx'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('school_year', 'number'), name='uniq_term_number_per_year'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['child', 'term'], name='assessment__child_i_8b8124_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['kindergarten', 'term'], name='assessment__kinderg_7ea75f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['enrollment', 'term'], name='assessment__enrollm_25ed54_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('child', 'enrollment', 'domain', 'term'), name='uniq_assessment_per_domain_term'),
        ),
    ]
