# Generated by Django 5.2.6 on 2026-08-12 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_term_kindergarten_and_assessed_at'),
        ('children', '0003_child_photo_historicalchild_photo'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TermReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('strengths', models.TextField(blank=True, verbose_name='давуу тал')),
                ('needs_support', models.TextField(blank=True, verbose_name='дэмжих шаардлагатай чадвар')),
                ('next_goals', models.TextField(blank=True, verbose_name='дараагийн улирлын зорилго')),
                ('advice_for_parents', models.TextField(blank=True, verbose_name='эцэг эхэд өгөх зөвлөмж')),
                ('status', models.CharField(choices=[('draft', 'Ноорог'), ('final', 'Дууссан')], db_index=True, default='draft', max_length=10, verbose_name='төлөв')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='дуусгасан огноо')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_reports', to='children.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_reports', to='children.enrollment')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='assessment.term', verbose_name='улирал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'улирлын тайлан',
                'verbose_name_plural': 'улирлын тайлан',
                'ordering': ['-term__number'],
                'indexes': [models.Index(fields=['child', 'term'], name='assessment__child_i_430e55_idx'), models.Index(fields=['kindergarten', 'term'], name='assessment__kinderg_53ee84_idx'), models.Index(fields=['enrollment', 'term'], name='assessment__enrollm_7fe4c1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('child', 'enrollment', 'term'), name='uniq_term_report_per_child_term')],
            },
        ),
    ]
