# Generated by Django 5.2.6 on 2026-08-09 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_child_photo_historicalchild_photo'),
        ('media', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='гарчиг')),
                ('body', models.TextField(verbose_name='үндсэн текст')),
                ('starts_on', models.DateField(blank=True, help_text='Хоосон бол нийтэлсэн даруйд харагдана', null=True, verbose_name='эхлэх огноо')),
                ('ends_on', models.DateField(blank=True, help_text='Хоосон бол хугацаагүй', null=True, verbose_name='дуусах огноо')),
                ('is_important', models.BooleanField(default=False, verbose_name='чухал')),
                ('status', models.CharField(choices=[('draft', 'Ноорог'), ('published', 'Нийтэлсэн')], default='draft', max_length=20, verbose_name='төлөв')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='нийтэлсэн огноо')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='нийтэлсэн багш')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'мэдэгдэл',
                'verbose_name_plural': 'мэдэгдлүүд',
                'ordering': ['-is_important', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='эрэмбэ')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='comms.announcement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='media.mediafile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'хавсралт',
                'verbose_name_plural': 'хавсралтууд',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='comms.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'уншсан тэмдэглэл',
                'verbose_name_plural': 'уншсан тэмдэглэлүүд',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='comms.announcement')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='children.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.group')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'хүлээн авагч',
                'verbose_name_plural': 'хүлээн авагчид',
            },
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['kindergarten', 'status', '-published_at'], name='comms_annou_kinderg_546740_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementattachment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('announcement', 'media_file'), name='uniq_attachment_per_announcement'),
        ),
        migrations.AddIndex(
            model_name='announcementread',
            index=models.Index(fields=['user', '-read_at'], name='comms_annou_user_id_ffa72e_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementread',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='uniq_read_per_user'),
        ),
        migrations.AddIndex(
            model_name='announcementtarget',
            index=models.Index(fields=['group'], name='comms_annou_group_i_feaa85_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementtarget',
            index=models.Index(fields=['child'], name='comms_annou_child_i_0a4912_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementtarget',
            constraint=models.CheckConstraint(condition=models.Q(('group__isnull', True), ('child__isnull', True), _connector='OR'), name='target_is_group_or_child_not_both'),
        ),
    ]
