# Generated by Django 5.2.6 on 2026-08-07 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(blank=True, max_length=20)),
                ('actor_label', models.CharField(blank=True, help_text='Хэрэглэгч устсан ч хэн байсныг мэдэхийн тулд', max_length=200)),
                ('action', models.CharField(choices=[('login', 'Нэвтэрсэн'), ('login_failed', 'Нэвтрэх оролдлого амжилтгүй'), ('logout', 'Гарсан'), ('view', 'Үзсэн'), ('create', 'Үүсгэсэн'), ('update', 'Зассан'), ('delete', 'Устгасан'), ('restore', 'Сэргээсэн'), ('download', 'Татсан'), ('export', 'Экспортолсон'), ('permission_change', 'Эрх өөрчилсөн'), ('password_reset', 'Нууц үг сэргээсэн')], db_index=True, max_length=32)),
                ('object_type', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(blank=True, help_text='Хүүхдийн мэдээлэлд хандсан бол — §971-ээр шүүх боломж', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='children.child')),
                ('kindergarten', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.kindergarten')),
            ],
            options={
                'verbose_name': 'үйлдлийн бүртгэл',
                'verbose_name_plural': 'үйлдлийн бүртгэл',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['child', '-created_at'], name='core_auditl_child_i_1709ca_idx'), models.Index(fields=['actor_user', '-created_at'], name='core_auditl_actor_u_8dc22f_idx'), models.Index(fields=['kindergarten', '-created_at'], name='core_auditl_kinderg_674891_idx'), models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx')],
            },
        ),
    ]
