# Generated by Django 5.2.6 on 2026-08-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Нэвтэрсэн'), ('login_failed', 'Нэвтрэх оролдлого амжилтгүй'), ('logout', 'Гарсан'), ('view', 'Үзсэн'), ('create', 'Үүсгэсэн'), ('update', 'Зассан'), ('delete', 'Устгасан'), ('restore', 'Сэргээсэн'), ('download', 'Татсан'), ('export', 'Экспортолсон'), ('permission_change', 'Эрх өөрчилсөн'), ('password_reset', 'Нууц үг сэргээсэн'), ('invite', 'Урилга үүсгэсэн'), ('activate', 'Бүртгэл идэвхжүүлсэн')], db_index=True, max_length=32),
        ),
    ]
