# Generated by Django 5.2.6 on 2026-08-07 15:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_name', models.CharField(max_length=100, verbose_name='овог')),
                ('first_name', models.CharField(max_length=100, verbose_name='нэр')),
                ('national_id', models.CharField(help_text='Давхцахгүй байх ёстой', max_length=32, verbose_name='регистр / дотоод код')),
                ('sex', models.CharField(choices=[('male', 'Эрэгтэй'), ('female', 'Эмэгтэй')], max_length=10, verbose_name='хүйс')),
                ('date_of_birth', models.DateField(verbose_name='төрсөн огноо')),
                ('enrolled_on', models.DateField(blank=True, null=True, verbose_name='элссэн огноо')),
                ('left_on', models.DateField(blank=True, null=True, verbose_name='гарсан огноо')),
                ('health_notes', models.TextField(blank=True, help_text='Анхаарах шаардлагатай мэдээлэл', verbose_name='эрүүл мэндийн товч тэмдэглэл')),
                ('status', models.CharField(choices=[('active', 'Идэвхтэй'), ('transferred', 'Шилжсэн'), ('graduated', 'Төгссөн'), ('archived', 'Архивлагдсан')], default='active', max_length=20, verbose_name='төлөв')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'хүүхэд',
                'verbose_name_plural': 'хүүхдүүд',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_on', models.DateField(verbose_name='элссэн огноо')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='дууссан огноо')),
                ('status', models.CharField(choices=[('active', 'Идэвхтэй'), ('transferred', 'Шилжсэн'), ('graduated', 'Төгссөн'), ('archived', 'Архивлагдсан')], default='active', max_length=20, verbose_name='төлөв')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='children.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='tenants.group')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='tenants.schoolyear')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'бүртгэл',
                'verbose_name_plural': 'бүртгэлүүд',
                'ordering': ['-started_on'],
            },
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('relation', models.CharField(choices=[('mother', 'Ээж'), ('father', 'Аав'), ('grandparent', 'Өвөө, эмээ'), ('other', 'Бусад')], max_length=20, verbose_name='хамаарал')),
                ('is_primary', models.BooleanField(default=False, verbose_name='үндсэн асран хамгаалагч')),
                ('can_view', models.BooleanField(default=True, help_text='Гэр бүлийн эрх зүйн шийдвэрээр хязгаарлагдсан тохиолдолд', verbose_name='мэдээлэл харах эрхтэй')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to='children.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('guardian_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'асран хамгаалагч',
                'verbose_name_plural': 'асран хамгаалагчид',
            },
        ),
        migrations.CreateModel(
            name='HistoricalChild',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_name', models.CharField(max_length=100, verbose_name='овог')),
                ('first_name', models.CharField(max_length=100, verbose_name='нэр')),
                ('national_id', models.CharField(help_text='Давхцахгүй байх ёстой', max_length=32, verbose_name='регистр / дотоод код')),
                ('sex', models.CharField(choices=[('male', 'Эрэгтэй'), ('female', 'Эмэгтэй')], max_length=10, verbose_name='хүйс')),
                ('date_of_birth', models.DateField(verbose_name='төрсөн огноо')),
                ('enrolled_on', models.DateField(blank=True, null=True, verbose_name='элссэн огноо')),
                ('left_on', models.DateField(blank=True, null=True, verbose_name='гарсан огноо')),
                ('health_notes', models.TextField(blank=True, help_text='Анхаарах шаардлагатай мэдээлэл', verbose_name='эрүүл мэндийн товч тэмдэглэл')),
                ('status', models.CharField(choices=[('active', 'Идэвхтэй'), ('transferred', 'Шилжсэн'), ('graduated', 'Төгссөн'), ('archived', 'Архивлагдсан')], default='active', max_length=20, verbose_name='төлөв')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.kindergarten')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical хүүхэд',
                'verbose_name_plural': 'historical хүүхдүүд',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['kindergarten', 'status'], name='children_ch_kinderg_e73b67_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['kindergarten', 'date_of_birth'], name='children_ch_kinderg_97842c_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['kindergarten', 'sex'], name='children_ch_kinderg_c3d765_idx'),
        ),
        migrations.AddIndex(
            model_name='child',
            index=models.Index(fields=['kindergarten', 'last_name', 'first_name'], name='children_ch_kinderg_be7cc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='child',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('kindergarten', 'national_id'), name='uniq_child_national_id'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['group', 'status'], name='children_en_group_i_386d0e_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['school_year', 'status'], name='children_en_school__a1a253_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['child', 'school_year'], name='children_en_child_i_eb875a_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('child', 'school_year'), name='uniq_enrollment_per_year'),
        ),
        migrations.AddIndex(
            model_name='guardianship',
            index=models.Index(fields=['guardian_user', 'can_view'], name='children_gu_guardia_bab436_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianship',
            index=models.Index(fields=['child'], name='children_gu_child_i_af65e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardianship',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('child', 'guardian_user'), name='uniq_guardianship'),
        ),
    ]
