# Generated by Django 5.2.6 on 2026-08-09 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_remove_enrollment_uniq_enrollment_per_year_and_more'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediafile', verbose_name='хүүхдийн зураг'),
        ),
        migrations.AddField(
            model_name='historicalchild',
            name='photo',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='media.mediafile', verbose_name='хүүхдийн зураг'),
        ),
    ]
