# Generated by Django 5.2.6 on 2026-08-07 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='нэр')),
                ('address', models.TextField(blank=True, verbose_name='хаяг')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='утас')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='и-мэйл')),
                ('description', models.TextField(blank=True, verbose_name='танилцуулга')),
                ('is_active', models.BooleanField(default=True, verbose_name='идэвхтэй')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'цэцэрлэг',
                'verbose_name_plural': 'цэцэрлэгүүд',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='ж: 2025-2026', max_length=20, verbose_name='нэр')),
                ('starts_on', models.DateField(verbose_name='эхлэх огноо')),
                ('ends_on', models.DateField(verbose_name='дуусах огноо')),
                ('is_current', models.BooleanField(default=False, verbose_name='одоогийн')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_years', to='tenants.kindergarten')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'хичээлийн жил',
                'verbose_name_plural': 'хичээлийн жилүүд',
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='нэр')),
                ('age_category', models.CharField(blank=True, max_length=50, verbose_name='насны ангилал')),
                ('timetable', models.TextField(blank=True, verbose_name='хичээлийн хуваарь')),
                ('rules', models.TextField(blank=True, verbose_name='бүлгийн дүрэм')),
                ('status', models.CharField(choices=[('active', 'Идэвхтэй'), ('archived', 'Архивлагдсан')], default='active', max_length=20, verbose_name='төлөв')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='tenants.schoolyear')),
            ],
            options={
                'verbose_name': 'бүлэг',
                'verbose_name_plural': 'бүлгүүд',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('primary', 'Үндсэн багш'), ('assistant', 'Туслах багш')], default='primary', max_length=20, verbose_name='үүрэг')),
                ('started_on', models.DateField(blank=True, null=True, verbose_name='эхэлсэн огноо')),
                ('ended_on', models.DateField(blank=True, null=True, verbose_name='дууссан огноо')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='tenants.group')),
                ('teacher_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='accounts.membership')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
            ],
            options={
                'verbose_name': 'бүлгийн багш',
                'verbose_name_plural': 'бүлгийн багш нар',
                'indexes': [models.Index(fields=['group', 'teacher_membership'], name='tenants_gro_group_i_34fe43_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='schoolyear',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('kindergarten', 'name'), name='uniq_school_year_name'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['kindergarten', 'status'], name='tenants_gro_kinderg_575447_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('school_year', 'name'), name='uniq_group_name_per_year'),
        ),
    ]
