# Generated by Django 5.2.6 on 2026-08-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='age_band',
            field=models.CharField(blank=True, choices=[('junior', 'Бага бүлэг'), ('middle', 'Дунд бүлэг'), ('senior', 'Ахлах бүлэг'), ('prep', 'Бэлтгэл бүлэг')], help_text='Бага (2 нас), Дунд (3), Ахлах (4), Бэлтгэл (5)', max_length=10, verbose_name='насны бүлэг'),
        ),
    ]
