# Generated by Django 5.2.6 on 2026-08-14 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_group_age_band'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('starts_at', models.TimeField(verbose_name='эхлэх цаг')),
                ('ends_at', models.TimeField(verbose_name='дуусах цаг')),
                ('activity', models.CharField(max_length=100, verbose_name='үйл ажиллагаа')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='тэмдэглэл')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='tenants.group')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'өдрийн дэглэмийн хэсэг',
                'verbose_name_plural': 'өдрийн дэглэм',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['group', 'starts_at'], name='tenants_rou_group_i_116360_idx')],
            },
        ),
    ]
