# Generated by Django 5.2.6 on 2026-08-09 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0002_remove_enrollment_uniq_enrollment_per_year_and_more'),
        ('observations', '0002_system_defaults'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='нийтийн ID')),
                ('purpose', models.CharField(choices=[('child_photo', 'Хүүхдийн зураг'), ('observation', 'Ажиглалтын хавсралт'), ('other', 'Бусад')], default='other', max_length=20, verbose_name='зориулалт')),
                ('storage_key', models.CharField(max_length=200, unique=True, verbose_name='хадгалалтын түлхүүр')),
                ('original_name', models.CharField(blank=True, help_text='Зөвхөн харуулах зориулалттай. Хадгалалтад хэрэглэхгүй.', max_length=255, verbose_name='файлын нэр')),
                ('mime_type', models.CharField(max_length=100, verbose_name='төрөл')),
                ('size_bytes', models.PositiveIntegerField(default=0, verbose_name='хэмжээ (байт)')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='өргөн')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='өндөр')),
                ('checksum', models.CharField(blank=True, help_text='Ижил файлыг таних, эвдэрсэн эсэхийг шалгах', max_length=64, verbose_name='sha256')),
                ('status', models.CharField(choices=[('uploading', 'Хуулж байна'), ('processing', 'Боловсруулж байна'), ('ready', 'Бэлэн'), ('failed', 'Амжилтгүй')], default='ready', max_length=20, verbose_name='төлөв')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='тайлбар')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='хуулсан огноо')),
                ('child', models.ForeignKey(blank=True, help_text='Хүүхдэд хамаарахгүй файл бол хоосон', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='children.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлууд',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='тайлбар')),
                ('taken_on', models.DateField(blank=True, null=True, verbose_name='зургийн огноо')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='эрэмбэ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('media_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observation_links', to='media.mediafile')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_links', to='observations.observation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ажиглалтын хавсралт',
                'verbose_name_plural': 'ажиглалтын хавсралтууд',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['child', 'purpose', '-uploaded_at'], name='media_media_child_i_9714d1_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['kindergarten', '-uploaded_at'], name='media_media_kinderg_222c49_idx'),
        ),
        migrations.AddConstraint(
            model_name='observationmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('observation', 'media_file'), name='uniq_media_per_observation'),
        ),
    ]
