# Generated by Django 5.2.6 on 2026-08-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='purpose',
            field=models.CharField(choices=[('child_photo', 'Хүүхдийн зураг'), ('observation', 'Ажиглалтын хавсралт'), ('announcement', 'Мэдэгдлийн хавсралт'), ('report', 'Үүсгэсэн тайлан'), ('other', 'Бусад')], default='other', max_length=20, verbose_name='зориулалт'),
        ),
    ]
