# Generated by Django 5.2.6 on 2026-08-09 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('children', '0002_remove_enrollment_uniq_enrollment_per_year_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='нэр')),
                ('code', models.SlugField(verbose_name='код')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='эрэмбэ')),
                ('is_active', models.BooleanField(default=True, verbose_name='идэвхтэй')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(blank=True, help_text='Хоосон бол системийн үндсэн жагсаалт', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten', verbose_name='цэцэрлэг')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ажиглалтын төрөл',
                'verbose_name_plural': 'ажиглалтын төрлүүд',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source', models.CharField(choices=[('teacher', 'Багш'), ('parent', 'Эцэг эх')], default='teacher', max_length=10, verbose_name='оруулсан')),
                ('observed_on', models.DateField(verbose_name='ажиглалтын огноо')),
                ('activity_name', models.CharField(blank=True, max_length=200, verbose_name='үйл ажиллагааны нэр')),
                ('situation', models.TextField(blank=True, verbose_name='нөхцөл байдал')),
                ('child_did', models.TextField(blank=True, verbose_name='хүүхдийн хийсэн үйлдэл')),
                ('child_said', models.TextField(blank=True, verbose_name='хүүхдийн хэлсэн үг')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='багшийн тайлбар')),
                ('next_steps', models.TextField(blank=True, verbose_name='дараагийн дэмжлэг, төлөвлөгөө')),
                ('visible_to_parents', models.BooleanField(default=True, verbose_name='эцэг эхэд харагдах')),
                ('include_in_report', models.BooleanField(default=True, verbose_name='тайланд оруулах')),
                ('review_status', models.CharField(choices=[('pending', 'Хүлээгдэж буй'), ('approved', 'Баталсан'), ('revision_requested', 'Засвар хүссэн')], default='approved', max_length=20, verbose_name='төлөв')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='хянасан огноо')),
                ('review_note', models.TextField(blank=True, verbose_name='хяналтын тэмдэглэл')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='children.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='children.enrollment')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='observations.observationtype', verbose_name='ажиглалтын төрөл')),
            ],
            options={
                'verbose_name': 'ажиглалт',
                'verbose_name_plural': 'ажиглалтууд',
                'ordering': ['-observed_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ObservationDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assessment.developmentdomain', verbose_name='хөгжлийн чиглэл')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assessment.assessmentlevel', verbose_name='үнэлгээ')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_links', to='observations.observation')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ажиглалтын чиглэл',
                'verbose_name_plural': 'ажиглалтын чиглэлүүд',
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('observation', 'domain'), name='uniq_domain_per_observation')],
            },
        ),
        migrations.AddConstraint(
            model_name='observationtype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('kindergarten__isnull', True)), fields=('code',), name='uniq_obs_type_system_code'),
        ),
        migrations.AddConstraint(
            model_name='observationtype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('kindergarten__isnull', False)), fields=('kindergarten', 'code'), name='uniq_obs_type_kindergarten_code'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['child', '-observed_on'], name='observation_child_i_d4ed7b_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['kindergarten', '-observed_on'], name='observation_kinderg_64d78c_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['enrollment', '-observed_on'], name='observation_enrollm_173809_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['source', 'review_status'], name='observation_source_fe8ec5_idx'),
        ),
    ]
