# Generated by Django 5.2.6 on 2026-08-16 13:30
"""§5.1 visibility closes by default — product decision, 2026-08-16.

Reviewed by hand (CLAUDE.md §3.4). Two things worth stating, because the
question this migration raises is "what happens to the records already in
the table":

* **Nothing.** ``manage.py sqlmigrate observations 0003`` prints ``(no-op)``.
  Django applies model defaults in Python rather than as a column default,
  so altering one changes what the *next* insert does and never touches a
  stored row. Observations a teacher has already published stay published,
  and families lose nothing they can see today. ``test_visibility_default``
  asserts it against real rows rather than trusting this note.
* It is reversible: the field is nullable-free either way and the operation
  carries no data step, so a rollback restores the previous default with no
  loss.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_system_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='visible_to_parents',
            field=models.BooleanField(default=False, verbose_name='эцэг эхэд харагдах'),
        ),
    ]
