# Generated by Django 5.2.6 on 2026-08-10 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_child_photo_historicalchild_photo'),
        ('media', '0002_alter_mediafile_purpose'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('type', models.CharField(choices=[('child_portfolio', 'Хүүхдийн хувийн хавтас')], default='child_portfolio', max_length=32, verbose_name='төрөл')),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='тохиргоо')),
                ('status', models.CharField(choices=[('queued', 'Дараалалд'), ('running', 'Боловсруулж байна'), ('done', 'Бэлэн'), ('failed', 'Амжилтгүй'), ('expired', 'Хугацаа дууссан')], db_index=True, default='queued', max_length=20, verbose_name='төлөв')),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, verbose_name='явц')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='файлын хэмжээ')),
                ('page_count', models.PositiveSmallIntegerField(default=0, verbose_name='хуудасны тоо')),
                ('error_message', models.TextField(blank=True, verbose_name='алдааны мэдээлэл')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='хүсэлт өгсөн')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='эхэлсэн')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='дууссан')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='хүчинтэй хугацаа')),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_jobs', to='children.child')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.kindergarten')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('result_media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media.mediafile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'тайлангийн хүсэлт',
                'verbose_name_plural': 'тайлангийн хүсэлтүүд',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['child', '-requested_at'], name='reports_rep_child_i_7af42b_idx'), models.Index(fields=['kindergarten', 'status', '-requested_at'], name='reports_rep_kinderg_322d67_idx')],
            },
        ),
    ]
