# Generated by Django 5.2.6 on 2026-08-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportjob',
            name='type',
            field=models.CharField(choices=[('child_portfolio', 'Хүүхдийн хувийн хавтас'), ('term_report', 'Улирлын тайлан')], default='child_portfolio', max_length=32, verbose_name='төрөл'),
        ),
    ]
